-- PostgreSQL legacy cleanup

BEGIN;

DROP TABLE IF EXISTS CreatorIndex CASCADE;
DROP TABLE IF EXISTS CreatorsCache CASCADE;
DROP TABLE IF EXISTS CreatorSearchCache CASCADE;
DROP TABLE IF EXISTS CreatorSnapshot CASCADE;
DROP TABLE IF EXISTS PopularSnapshot CASCADE;
DROP TABLE IF EXISTS PreviewAssetCache CASCADE;
DROP TABLE IF EXISTS MediaSourceCache CASCADE;
DROP TABLE IF EXISTS FavoriteSnapshot CASCADE;

COMMIT;
